imports_granularity="Crate"
indent_style = "Block"
combine_control_expr=true
edition="2021"
format_code_in_doc_comments=true
format_generated_files=true
format_macro_matchers=true
format_macro_bodies=true
format_strings=true
hard_tabs=true